### ISSUE TITLE
Opening a Dialog during initial page load doesn't work

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-dialog-flow#32]
Calling `Dialog.open();` during the initial page load doesn't seem to add `<vaadin-dialog-overlay>` etc. to the DOM.

Demo app: [test_app.zip](https://github.com/vaadin/vaadin-dialog-flow/files/1707744/test_app.zip)
run `mvn jetty:run` and navigate to http://localhost:8080/customer/1/edit

```java
@Route(value = "customer", layout = MainView.class)
public class CustomerDetailsRoute extends Composite<CustomerDetailsView> implements HasUrlParameter<String> {

	@Override
	public void setParameter(BeforeEvent event, @WildcardParameter String parameter) {
		boolean openEditor = false;
		Long id;
		if (parameter.contains("/")) {
			String[] params = parameter.split("/");
			id = Long.parseLong(params[0]);
			openEditor=true;
		} 
		else {
			id = Long.parseLong(parameter);
		}
		CustomerService service = VaadinSession.getCurrent().getAttribute(CustomerService.class);
		Customer customer = service.getById(id);
		getContent().setCustomer(customer);
		if (openEditor) {
			CustomerForm customerForm = new CustomerForm();
			customerForm.setCustomer(customer);
			Dialog dialog = new Dialog(customerForm);
			// this doesn't seem to work:
			dialog.open();
			// Clicking this button does open the dialog
			getContent().getElement().appendChild(new Button("asd", e -> dialog.open()).getElement());
		}
	}

}

```

**Comment by denis-anisimov** [comment]
This is not strictly related to the `Dialog` itself.
The `Dialog`  is a regular component which needs to be added to some container.
The `open` method works only if the component is added (and it's in DOM tree on the client side).
To be able to avoid unclear component addition along with the `open`  method usage the method is implemented in the way to add the `Dialog` instance to `UI`.
The problem is that all `UI`  children are removed when routing is used. So the `Dialog`  instance is just removed from the `UI`  instance (replaced by the routing components) if it calls `open()` during the view initialization.
