### ISSUE TITLE
DetachListeners are never called

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-dialog-flow#36]
DetachListeners are never called. e.g. here the 'Dialog was detached' notification is never shown when closing the dialog.

```
public class MainView extends Div {
    public MainView() {
        Dialog dialog = new Dialog(new Paragraph(
            "Closing this dialog should call a detach listener which shows a notification 'Dialog was detached'"));
        dialog.open();

        dialog.addDetachListener(e -> {
            Notification.show("Dialog was detached", 1000, Position.MIDDLE);
        });

        add(
            new Paragraph("This is the host page"),
            new Button("Open dialog", e -> dialog.open()),
            new Button("Notification test", e -> Notification.show("Blah blah blah", 1000, Position.MIDDLE))
        );
    }

}
```

Minimal test app: [dialog_test.zip](https://github.com/vaadin/vaadin-dialog-flow/files/1719333/dialog_test.zip)
run with `mvn jetty:run` and open the UI at http://localhost:8080

**Comment by pekam** [comment]
Closing the dialog removes it from the DOM since https://github.com/vaadin/vaadin-dialog-flow/pull/44, so the detach listener is called.

However, this doesn't apply when you attach the Dialog manually to the DOM. When you add the component, you take the responsibility to remove it too.

So using a detach listener is not a reliable way for listening for closing the Dialog. Instead you should use `OpenedChangeListener`, which is now emphasized in the javadocs.
