### ISSUE TITLE
Add close listener support where it's possible to cancel the closing of a Dialog

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-dialog-flow#37]
Really useful feature e.g. when user has entered some unsaved changes in a form that is presented inside a Dialog. End-user can accidentally hit Escape or click the outside area of the Dialog and lose any unsaved changes.

**Comment by Legioth** [comment]
There's a practical challenge here since a round trip would be needed for making the decision. This does in practice mean that the actual listener on the client side would need to know whether the server side might potentially want to cancel the user action, and in that case do a full cancel and then separately trigger a programmatic close if the server later on reports that the listener did indeed allow the dialog to be closed.

**Comment by pleku** [comment]
I can't see this happening properly without element support. In optimal case it would work even without the roundtrip, eg. if some property is true (controlled by the server side), the will not close without confirmation dialog, which can be preset already. "Unfinished changes, are you sure you want to cancel ?"

**Comment by pleku** [comment]
Currently this can be implemented in a template with some latency compensation magic.

**Comment by manolo** [comment]
Related with https://github.com/vaadin/vaadin-dialog/issues/56

**Comment by manolo** [comment]
pls add `app starter` label
