### ISSUE TITLE
Cannot set focus on child element when opening

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-dialog-flow#55]
When opening a dialog, I cannot give focus to a child element (e.g. `TextField`) since the focus is always set by the dialog element itself.

Code to reproduce:

```java
TextField field = new TextField();
Dialog dialog = new Dialog(field);
dialog.addOpenedChangeListener(event -> field.focus());
dialog.open();
```

Then `field` won't have focus, but the dialog will, i.e. in Firefox you will see a dotted outline:

<img width="344" alt="screen shot 2018-04-03 at 17 43 15" src="https://user-images.githubusercontent.com/851745/38259914-8f1ebeb6-3766-11e8-9d71-102cfca225bf.png">

**Comment by pleku** [comment]
Caused probably by the way we do things to circumvent https://github.com/vaadin/vaadin-dialog/issues/51

**Comment by tomivirkki** [comment]
Shouldn't be related to the shadow root. If this has worked before, my guess is that it's a regression from https://github.com/vaadin/vaadin-overlay/pull/69/

**Comment by pleku** [comment]
@heruan which version of `vaadin-overlay` was used? Can you reproduce this issue with V10 beta6 ?

**Comment by heruan** [comment]
I can reproduce with V10 beta6, which brings `vaadin-overlay` version 2.1.0.

`jetty:run` this to reproduce: https://github.com/heruan/flow-test/tree/dialog-focus

**Comment by manolo** [comment]
The problem is that latest overlay focuses itself on opening. This is done in this way in order to solve other issues like scrolling with keyboard, or not triggering the opening of soft keyboard in touch devices.

Your code does not work because focus of the overlay happens after the server focuses the field. It's not a problem in flow, since in pure polymer it neither works, e.g. this code does not focus the field.
```
  overlay.opened = true;
  myfield.focus();
```

I guess the best option for having a full control on what field should be focused on opening is to implement the feature of the `autofocus` attribute. Thus the overlay would focus the first element that has that attribute.

**Comment by manolo** [comment]
Discussed with the team, we decided not to focus the overlay if the content is already focused, it should fix your issue.
In the meanwhile we release a new version, and it's included in vaadin platform, you can workaround by setting the `tabindex` of the field. This code works to me.

```
        TextField textField = new TextField();
        textField.setTabIndex(1);
        Dialog dialog = new Dialog(textField);
        this.add(new Button("Open dialog", event -> dialog.open()));
```

**Comment by pleku** [comment]
We should add an UI test for this to `Dialog`.
