### ISSUE TITLE
Different overlay content structure

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-dialog-flow#69]
Depending on how the dialog is attached to the page, overlay's content node has different structure.

1. Dialog is declared inside polymer template `<vaadin-dialog id="dialog"></vaadin-dialog>` and bound by `@Id` on server-side
```
...
  <div id="content">
    #shadow-root
      <flow-component-renderer>
         <div>     -------> light DOM
```
2. Dialog object is created on server and attached to the page automatically when opened.
```
...
<vaadin-dialog-overlay>
   <flow-component-renderer>   --------> light DOM (slotted into div content)
         <div>     -------> light DOM
```

There is no way to style the `div` in 2nd case, except using dialog-flow API, which allows to set only height, width and color. Are the any plans to support setting arbitrary styles?

Is it possible that overlay would always have the same structure?

**Comment by denis-anisimov** [comment]
It looks like there are several confusions in many places.

First of all here is the java code for the reference (at least can be used in our test infrastructure along with `dialog` `flow-data` dependencies):
```java
@Route(value = "xx", layout = ViewTestLayout.class)
@HtmlImport("frontend://com/vaadin/flow/uitest/ui/template/A.html")
@Tag("a-a")
public class AView extends PolymerTemplate<TemplateModel>
        implements HasComponents {

    private @Id Dialog dialog;

    public AView() {
        NativeButton a = new NativeButton("Injected", event -> dialog.open());
        NativeButton b = new NativeButton("Java dialog", event -> {
            Dialog javaDialog = new Dialog();
            Div div = new Div();
            div.setText("bbbbbbbbbbbb");
            javaDialog.add(div);
            javaDialog.open();
        });
        add(a, b);
    }
}
```

here is the template file:
```html
<link rel="import" href="/frontend/bower_components/polymer/polymer-element.html">
<link rel="import" href="/frontend/bower_components/vaadin-dialog/vaadin-dialog.html">

<dom-module id="a-a">
    <template>
        <vaadin-dialog id="dialog">
        <template>
        <div>XX</div>
      </template>
        </vaadin-dialog>
        <slot></slot>
    </template>
    <script>
        class A extends Polymer.Element {
            static get is() { return 'a-a' }

        }
        customElements.define(A.is, A);
    </script>
</dom-module>
```

The resulting DOM is different from the examples in the description.
This is the DOM tree with injected dialog: 
 
<img width="622" alt="screen shot 2018-06-07 at 10 49 33 am" src="https://user-images.githubusercontent.com/11425472/41085841-c5b9c33c-6a40-11e8-8fdb-58791dac0604.png">

This is the DOM tree with a dialog attached via Java:

<img width="625" alt="screen shot 2018-06-07 at 10 50 04 am" src="https://user-images.githubusercontent.com/11425472/41085846-ca0d3a9a-6a40-11e8-9237-169c0105677a.png">

The overlay element (element in the  `vaadin-dialog-overlay` with `overlay` id) is almost the same except:
- with the web-component dialog there is a shadow root and the content of the dialog is a part of shadow root.
- in java case there is no shadow root. There is a slot instead and the `flow-component-renderer`  element is inside this slot, though technically it's a child of `vaadin-dialog-overlay`. And the content is a direct child of the `flow-component-renderer` element .

So questions:
> There is no way to style the div in 2nd case, except using dialog-flow API
- I'm not sure which style you are talking about. But since `flow-component-renderer`   is a child of `vaadin-dialog-overlay` and both of them in the normal DOM ( not is shadow root ) you definitely may style everything inside `flow-component-renderer` .
- Yes, the structure is different and you will have to style content differently in those two cases.
>Is it possible that overlay would always have the same structure?
- I'm not sure about answer to this question. It looks like it should be possible. But I have to ask the expert who knows about the implementation and reasons why it's done in this way.

**Comment by denis-anisimov** [comment]
@gilberto-torrezan , could you please look into that?
The main question: 
>Is it possible that overlay would always have the same structure?

As I understand the code which adds a content inside the dialog overlay is inside `flow-component-renderer.html`.

I have two questions. One is related to this issue and another one is almost unrelated:
- The code adds a child to the `flow-component-renderer` element (if I get it right). As I understand it should be possible to modify shadow root of the content element instead of using `flow-component-renderer` as a parent. In this case the local DOM structure in the dialog overlay will be the same as for web-component case. So can we do it so the structure will be the same in both cases?
- Do we need `flow-component-renderer` element at all? It's added as a child but it has programmatic nature only. Its purpose is to add/replace the element in the local DOM. It's not a big deal that it's in the local DOM (it seems) and we have extra unneeded element but wouldn't it be enough to have a JS attached to the Dialog which does similar things without this template magic?

**Comment by denis-anisimov** [comment]
OK, thanks.
Not sure what to do with this ticket....

I think you may create a ticket for the same DOM structure in dialog ( and notification) but may be it won't be fixed. At least we will be able to track it.
I would suggest to close this ticket if you don't mind since there are no actions to do.....

**Comment by alexberazouski** [comment]
Thanks for the detailed overview.
But what about the CSS styling of the `div` in the Java approach?
There is no convenient way to style it. I can set `height&width` via Java API

**Comment by denis-anisimov** [comment]
What do you mean about styling ?
You may add a style name to the div. And then you may use this style name in the CSS file.
What exactly you would like to do ?

**Comment by alexberazouski** [comment]
I don't see any possibility to set the class name for a `div` wrapper.
I'm talking about this `div`:
https://github.com/vaadin/vaadin-dialog-flow/blob/master/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L56

**Comment by denis-anisimov** [comment]
Aaaah.
OK, now I got it.
Yeah. This div is kind of extra. You don't have an access to it.
You still can make a selector for it (e.g. `flow-component-renderer > div`) but it's not convenient, true.

OK, I will create a ticket for this.

**Comment by denis-anisimov** [comment]
#76 is created.
